StudentsCircle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminn/', include('adminn.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('student.urls')),
    path('union/', include('union.urls')),
    # path('chat/', include('chat.urls')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# userprofile  = timeline.html/pitpoint-detail.html/pittube-channel.html/
# youtube brain wash for code: - mr robots, cilicon vally

chat/urls.py
from django.urls import path
from .views import index, room
app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),

]

student/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UserHomeView, add_comment, add_like, Timeline, \
    ProfileView, Friends, Unions, edit_fullname, edit_profile_data, \
    select_my_union, upload_pp, chat_room


app_name = 'student'


urlpatterns = [
    path('', UserHomeView.as_view(), name='home'),

    path('add_cmnt/', add_comment, name='add_cmnt'),
    path('add_like/', add_like, name='add_like'),
    path('edit_fullname/', edit_fullname, name='edit_fullname'),
    path('edit_profile_data/', edit_profile_data, name='edit_profile_data'),
    path('select_my_union/', select_my_union, name='select_my_union'),
    path('upload_pp/', upload_pp, name='upload_pp'),
    path('chat_room/<int:pk>', chat_room, name='chat_room'),

    path('posts/<int:pk>', UserHomeView.as_view(), name='detail'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('timeline/', Timeline.as_view(), name='timeline'),
    path('friends/', Friends.as_view(), name='friends'),
    path('unions/', Unions.as_view(), name='unions'),



]

union/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import UnionDetailView, MyUnionDetailView, UnionAdminView, union_join_req

app_name = 'union'

urlpatterns = [
    path('details/<int:pk>', UnionDetailView.as_view(), name='details'),
    path('my_union', MyUnionDetailView.as_view(), name='my_union'),
    path('union_admin', UnionAdminView.as_view(), name='union_admin'),
    path('join_req/', union_join_req, name='union_join_req'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_save


# Create your models here.


class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True, unique=True)
    email = models.EmailField(max_length=150, blank=True, null=True, unique=True)
    is_verified = models.BooleanField(default=False)
    is_union = models.BooleanField(default=False)
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return str(self.username)

    def get_absolute_url(self):
        return reverse('student:details', args=[self.pk])


class Union(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    reg_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    est_date = models.DateField(null=True, blank=True)
    background_img = models.ImageField(upload_to='bg_pic/', height_field=None, width_field=None, null=True)
    logo = models.ImageField(upload_to='union_logo/', height_field=None, width_field=None, null=True)
    college_name = models.CharField(max_length=150, blank=True, null=True)
    college_short_name = models.CharField(max_length=30, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    college_est_date = models.DateField(null=True, blank=True)
    college_logo = models.ImageField(upload_to='collage_logo/', height_field=None, width_field=None, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created

    def __str__(self):
        return str(self.user)


GENDER = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default='Male', null=True, blank=True)
    admission_num = models.BigIntegerField(blank=True, null=True, unique=True)
    batch = models.CharField(max_length=200, blank=True, null=True)
    batch_num = models.BigIntegerField(blank=True, null=True, unique=True)
    union = models.ForeignKey(Union, on_delete=models.CASCADE, blank=True, null=True)
    membership_num = models.CharField(max_length=20, blank=True, null=True, unique=True)
    membership_img = models.ImageField(upload_to='memb_pic/', height_field=None, width_field=None, blank=True,
                                       null=True)
    profile_img = models.ImageField(upload_to='profile_pic/', height_field=None, width_field=None, blank=True,
                                    null=True)
    background_img = models.ImageField(upload_to='bg_pic/', height_field=None, width_field=None, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)  # set when created
    # general info
    hobbies = models.TextField(blank=True, null=True)
    interests = ArrayField(models.CharField(max_length=10, default='Arabic', blank=True, null=True), null=True)


def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Student.objects.create(user=instance)
        except:
            pass
# post_save.connect(post_save_user_model_receiver, sender=User)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_user')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


# Explorer, Talker, Admirer, Searcher, Groups and Events


class PointBadges(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userbadge')
    point = models.BigIntegerField(blank=True, null=True)
    badge = ArrayField(models.CharField(max_length=10, default="starter", blank=True, null=True), null=True)


class MemberRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='from_member')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='to_member')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

    def __str__(self):
        return "From {}, to {}".format(self.from_user.username, self.to_user.username)


class PageAdmin(models.Model):
    page = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='page')
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin')
    timestamp = models.DateTimeField(auto_now_add=True)  # set when created

chat/models.py
from django.db import models

# Create your models here.

student/models.py
import uuid

from accounts.models import User
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.urls import reverse
from django.utils.text import slugify

# from .signals import delete_post_image , resize_post_image
from .utils import number, incrementor
from django.utils import timezone
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer


# Create your models here.


def upload_post_to(instance, filename):
    return f'post_image/{instance.user.username}/{filename}'


class PostManager(models.Manager):
    def get_posts(self, status: bool = False):
        return (
            self.get_queryset()
                .select_related("user", "user__profile")
                .prefetch_related("likes__profile", "comment_set__user__profile")
                .filter(archived=status)
        )


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=250, unique=False, null=True)
    image = models.ImageField(null=True, blank=True, upload_to='post_images/', )
    # likes = models.ManyToManyField(User, related_name="likes", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} : {self.text[:10]}"

    @property
    def image_url(self):
        if self.image == '':
            image = ''
        else:
            image = self.image.url
        return image

    def save(self, *args, **kwargs):
        self.slug = slugify(self.text[:5] + str(number()))
        if not self.image:
            self.image = ""
        if not self.text:
            self.text = ""
        return super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-created"]

    # to find url for each post
    def get_absolute_url(self):
        return reverse('student:detail', args=[self.slug])


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} : {self.user}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()


class SubComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    sub_com = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


# post_delete.connect(delete_post_image, sender=Post)
# post_save.connect(resize_post_image, sender=Post)


class Room(models.Model):
    room_name = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True, editable=False)
    user1 = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user2')


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='m_from_user')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='m_to_user')
    message_type = models.CharField(max_length=10, default='text')
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    message = models.TextField('message')
    msg_img = models.ImageField(upload_to='msg_img/', height_field=None, width_field=None, blank=True, null=True)
    vid_img = models.FileField(upload_to='vid_img/', blank=True, null=True)
    aud_img = models.FileField(upload_to='aud_img/', blank=True, null=True)
    pdf_img = models.FileField(upload_to='pdf_img/', blank=True, null=True)




# class MessageModel(models.Model):
#     """
#     This class represents a chat message. It has a owner (user), timestamp and
#     the message body.
#
#     """
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user',
#                       related_name='m_from_user', db_index=True)
#     recipient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='recipient',
#                            related_name='m_to_user', db_index=True)
#     timestamp = models.DateTimeField('timestamp', auto_now_add=True, editable=False,
#                               db_index=True)
#     body = models.TextField('body')
#
#     def __str__(self):
#         return str(self.id)
#
#     def characters(self):
#         """
#         Toy function to count body characters.
#         :return: body's char number
#         """
#         return len(self.body)
#
#     def notify_ws_clients(self):
#         """
#         Inform client there is a new message.
#         """
#         notification = {
#             'type': 'recieve_group_message',
#             'message': '{}'.format(self.id)
#         }
#
#         channel_layer = get_channel_layer()
#         print("user.id {}".format(self.user.id))
#         print("user.id {}".format(self.recipient.id))
#
#         async_to_sync(channel_layer.group_send)("{}".format(self.user.id), notification)
#         async_to_sync(channel_layer.group_send)("{}".format(self.recipient.id), notification)
#
#     def save(self, *args, **kwargs):
#         """
#         Trims white spaces, saves the message and notifies the recipient via WS
#         if the message is new.
#         """
#         new = self.id
#         self.body = self.body.strip()  # Trimming whitespaces from the body
#         super(MessageModel, self).save(*args, **kwargs)
#         if new is None:
#             self.notify_ws_clients()
#
#     # Meta
#     class Meta:
#         app_label = 'student'

chat/views.py
from django.shortcuts import render


# Create your views here.


def index(request):
    return render(request, 'chat/index.html', {})


def room(request, room_name):
    # context = ''
    # context['room_name'] = room_name
    return render(request, 'chat/catroom.html', {'room_name': room_name})

union/views.py
import requests
from django.contrib.auth.decorators import login_required

from accounts.models import Student, Union, User, MemberRequest, FriendRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, DetailView
from student.forms import CreatePostForm
from student.models import Post
from student.views import UserHomeView


# Create your views here.


class UnionDetailView(DetailView):
    model = User
    template_name = 'union/union_detail.html'

    def get_context_data(self, **kwargs):
        context = super(UnionDetailView, self).get_context_data(**kwargs)
        user = self.request.user
        username = kwargs['object']
        union = User.objects.get(username=username)
        members = Student.objects.filter(union=union.pk)
        last_post = union.pk
        post = Post.objects.filter(user=union.pk).order_by('-created').first()

        context['user'] = user
        context['post'] = post
        context['union'] = union
        context['members'] = members
        return context


class MyUnionDetailView(LoginRequiredMixin, View):
    template_name = 'union/my_union.html'

    def get(self, request: WSGIRequest) -> HttpResponse:
        union = request.user.student.union
        members = Student.objects.filter(union=union.pk)
        union_post = Post.objects.filter(user=union.pk)

        context = {"union": union, "members": members, "union_post": union_post}
        return render(request, self.template_name, context)


class UnionAdminView(LoginRequiredMixin, View):
    template_name = 'union/union_admin_panel.html'

    def get(self, request: WSGIRequest) -> HttpResponse:
        post_form = CreatePostForm()
        union = request.user.student.union
        members = Student.objects.filter(union=union)
        member_requests = FriendRequest.objects.filter(to_user=union.user)

        context = {"union": union, "post_form": post_form, "members": members, 'member_requests': member_requests}
        return render(request, self.template_name, context)

    def post(self, request: WSGIRequest) -> HttpResponse:
        post_form = CreatePostForm(request.POST, request.FILES)
        union = request.user.student.union.user

        if post_form.is_valid():
            obj = post_form.save(commit=False)
            obj.user = union
            obj.save()
            return redirect('union:my_union')

        context = {"post_form": CreatePostForm()}
        return render(request, self.template_name, context)


@login_required(login_url='/accounts/login')
def union_join_req(request):
    union_id = request.POST['union_id']
    user_id = request.POST['user_id']
    value = request.POST['value']
    user = get_object_or_404(User, id=user_id)
    union = get_object_or_404(Union, user=union_id)

    if value == 'Accept':
        j_request = FriendRequest.objects.filter(
            from_user=user_id,
            to_user=union_id).first()
        user.is_verified = True
        user.student.union = union
        user.save()
        user.student.save()
        j_request.delete()
        return JsonResponse('Remove', safe=False)
    elif value == 'Reject':
        j_request = FriendRequest.objects.filter(
            from_user=user_id,
            to_user=union_id).first()
        j_request.delete()
        return JsonResponse('false', safe=False)
    elif value == 'Remove':
        user.student.union.remove(union_id)
        return JsonResponse('false', safe=False)

templates/student/profile_head.html
<!--{% load static %}-->
<div class="user-profile">
    <figure>
        <div class="edit-pp">
            <label class="fileContainer">
                <i class="fa fa-camera"></i>
                <input type="file">
            </label>
        </div>
        <img src="{% static 'user/images/resources/profile-image.jpg' %}" alt="">

<!--        <ol class="pit-rate">-->
<!--            <li class="rated"><i class="fa fa-star"></i></li>-->
<!--            <li class="rated"><i class="fa fa-star"></i></li>-->
<!--            <li class="rated"><i class="fa fa-star"></i></li>-->
<!--            <li class="rated"><i class="fa fa-star"></i></li>-->
<!--            <li class=""><i class="fa fa-star"></i></li>-->
<!--            <li><span>4.7/5</span></li>-->
<!--        </ol>-->
    </figure>

    <div class="profile-section">
        <div class="row">
            <div class="col-lg-2 col-md-3">
                <div class="profile-author">
                    <div class="profile-author-thumb">
                        {% if user.student.profile_img %}
                        <img id="cropped" alt="author"  src=" {{ user.student.profile_img.url }} ">
                        {% else %}
                        <img id="cropped" alt="cropped" src="{% static 'user/images/male.png' %}">
                        {% endif %}
                        <form action="/upload_pp/" method="post">
                            {% csrf_token %}
                            <textarea name="profile_pic" id="profile_pic" cols="30" rows="10" hidden></textarea>
                            <input id="pp_save_btn" type='submit' class="btn btn-success mt-2" value="save" hidden>
                        </form>
                        <div class="edit-dp">
                            <label class="fileContainer">
                                <i class="fa fa-camera"></i>
                                <input type="file" id="imagecrp" name="imagecrp" accept="image/*"
                                   oninput="imagecrp.src=window.URL.createObjectURL(this.files[0])"
                                   style="" class="form-control file-upload-info" required>
                            </label>
                        </div>
                    </div>

<!-- croppter =======================================================================-->
                    <!--MODEL-->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Crop Image</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" >
                                    <div class="box-2">
                                        <div class="result" style="height:100%"></div>
                                    </div>
                                </div>
                                <div class="modal-footer">

                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                        Close
                                    </button>

                                    <button type="button" id="load" class="btn save btn-primary">
                                        Save changes
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- model end-->

<!--                    <div class="crop-picker-wrap">-->
<!--                        <button class="crop-picker" id='select' type="button">Select Image</button>-->
<!--                        <input type="file" class="crop-picker-file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">-->
<!--                    </div>-->
<!--&lt;!&ndash;                        Preview&ndash;&gt;-->
<!--                    <div id="preview">-->
<!--&lt;!&ndash;                        {% if thumb_pic %}&ndash;&gt;-->
<!--&lt;!&ndash;&lt;!&ndash;                        <img src="{{MEDIA_URL}}{{thumb_pic}}" id="target" />&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;                        {% else%}&ndash;&gt;-->
<!--                        <img src="" id="target" />-->
<!--&lt;!&ndash;                        {% endif %}&ndash;&gt;-->
<!--                        <span>Scroll to zoom in or out</span>-->
<!--                    </div>-->
<!--&lt;!&ndash;                    Show the effect of cropping&ndash;&gt;-->
<!--                    <div id="preview-pane">-->
<!--                        <div class="preview-container">-->
<!--                            <img src="" id="cut_thumb"/>-->
<!--                        </div>-->
<!--                        <span>160*160</span>-->
<!--                    </div>-->

<!--                    <div class="crop-operate">-->
<!--                        <button class="crop-save" type='submit' id='save'>save</button>-->
<!--                        <button class="crop-cancel" type="button" id='cancel'>cancel</button>-->
<!--                    </div>-->
<!-- croppter =======================================================================-->



                    <div class="author-content">
                        <a class="h4 author-name" href="about.html">{{ user.username|capfirst }}</a>
                        {% if user.is_verified %}
                        <div class="country">{{ user.student.union|title }}</div>
                        {% else %}
                        <div class="country text-danger">Not verified</div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-10 col-md-9">
                <ul class="profile-menu">
                    <li>
                        <a class="" href="{% url 'student:profile' %}">About</a>
                    </li>
                    <li>
                        <a class="" href="{% url 'student:timeline' %}">Timeline</a>
                    </li>
                    {% if user.is_verified %}
                    <li>
                        <a class="" href="{% url 'student:friends' %}">Friends</a>
                    </li>
                    <li>
                        <a class="" href="{% url 'student:unions' %}">Unions</a>
                    </li>
                    {% endif %}
<!--                    <li>-->
<!--                        <a class="" href="timeline-videos.html">Videos</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <div class="more">-->
<!--                            <i class="fa fa-ellipsis-h"></i>-->
<!--                            <ul class="more-dropdown">-->
<!--                                <li>-->
<!--                                    <a href="timeline-groups.html">Profile Groups</a>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <a href="statistics.html">Profile Analytics</a>-->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                    </li>-->
                </ul>
                <ol class="folw-detail">
<!--                    <li><span>Points</span><ins>101</ins></li>-->
                    <li><span>Posts</span><ins>{{ user.post_set.count }}</ins></li>
                    <li><span>Followers</span><ins>{{ user.friends.count }}</ins></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/0.8.1/cropper.min.js"></script>
<!----------------------------------------->
<!-----------------cropping----------------->
<script>
var imgSrc;
let result = document.querySelector(".result"),
    save = document.querySelector("#load"),
    cropped = document.querySelector("#cropped"),
    upload = document.querySelector("#imagecrp"),
    cropper = "";

upload.addEventListener("change", (e) => {
    if (e.target.files.length) {
        const reader = new FileReader();

        reader.onload = (e) => {
            if (e.target.result) {
                // create new image
                $("#exampleModalCenter").modal("show");
                let img = document.createElement("img");
                img.id = "image";
                img.src = e.target.result;

                result.innerHTML = "";

                result.appendChild(img);
                cropper = new Cropper(img, {
                    viewMode: 2,
                    aspectRatio: 1/1,
                    autoCropArea: 1,
                    crop: function (e) {
                        console.log(e.detail.x);
                        console.log(e.detail.y);
                    }
                });
            }
        };
        reader.readAsDataURL(e.target.files[0]);
    }
});

save.addEventListener("click", (e) => {
    e.preventDefault();
    console.log('hello----------------');
    imgSrc = cropper
        .getCroppedCanvas({
            width: 300,
            height: 300,
        })
        .toDataURL();
    $("#exampleModalCenter").modal("hide");
    cropped.src = imgSrc;
    $('#profile_pic').val(cropped.src)
    $('#pp_save_btn').removeAttr('hidden');
});
</script>
<script src="{% static 'user/js/my-js.js' %}"></script>